version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=final'
      - 'MYSQL_PASSWORD=12341234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=final'
    ports:
      - '3306:3306'  # 호스트의 3306 포트를 컨테이너의 3306 포트로 매핑
    volumes:
      - mysql-data:/var/lib/mysql  # 데이터 영속성을 위한 볼륨 추가

#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379:6379'  # 호스트의 6379 포트를 컨테이너의 6379 포트로 매핑

# 영속성을 위한 볼륨 정의
volumes:
  mysql-data:
