services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=final"
      - "MYSQL_PASSWORD=12341234"
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_USER=final"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    mem_limit: 512m

  flask:
    build:
      context: ../flask
    container_name: flask_app
    ports:
      - "5001:5000"
    depends_on:
      - elasticsearch
      - redis
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_URL=redis://redis:6379/0
    networks:
      - backend
    command: ["supervisord", "-c", "/etc/supervisord.conf"]  # supervisord로 Flask와 RQ 워커 동시에 실행

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.ml.enabled=false"
      - "indices.fielddata.cache.size=50%"
      - "indices.query.bool.max_clause_count=1024"
      - "action.destructive_requires_name=true"
    ports:
      - "9200:9200"
    networks:
      - backend
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1


volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
  mysql-network:
    driver: bridge
